spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/popo?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

jwt:
  accessToken_exp_time: 3600 #1시간
  refreshToken_exp_time: 43200 #12시간
  secret: ${JWT_SECRET_KEY}
